#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
General stationary-domain detector for microscopy images and numerical property maps.

Purpose
-------
This script creates strict stationary-domain masks before any REV calculation.
It generalizes the previous BSE/gray-image mask detector so that the same idea
can be applied to numerical property fields such as

    kappa(x,y) [W m^-1 K^-1], E(x,y) [GPa], nu(x,y) [-]

stored as CSV maps, or to ordinary image files such as TIFF/PNG BSE maps.

Scientific logic
----------------
For a scalar field Z(x,y), the code scans the full map with local square
stationarity windows of side R. For each stationarity window W_p it computes

    mu_p    = mean(Z in W_p)
    sigma_p = std(Z in W_p)

The robust image-level references are the medians of all local means and local
standard deviations. A stationarity window is accepted when both normalized
residuals satisfy the prescribed tolerances:

    |mu_p - median(mu)|       / (|median(mu)|    + eps) <= tau_mu
    |sigma_p - median(sigma)| / (|median(sigma)| + eps) <= tau_sigma

Accepted stationarity windows are converted into a pixel-level mask. Small
isolated components can be removed, and optionally only the largest connected
component can be retained.

Input modes
-----------
1. Single-field mode:
       python detect_stationary_domains_general.py field1.csv field2.csv ...

   Use this for BSE images, kappa maps, E maps, or nu maps separately.

2. Property-map mode:
       python detect_stationary_domains_general.py \
           --kappa-maps kappaMap_1.csv ... kappaMap_7.csv \
           --E-maps     EMap_1.csv     ... EMap_7.csv     \
           --nu-maps    nuMap_1.csv    ... nuMap_7.csv    \
           --stationarity-source combined

   Use this to build masks on the property-map grid. The stationarity source
   can be kappa, E, nu, or combined. For combined, the code robustly standardizes
   each available channel and combines them into a scalar structural field.

Important notes
---------------
* Use CSV numerical property maps, not TIFF visualization maps generated by
  mat2gray/imwrite. TIFF visualization maps are rescaled intensities and do not
  preserve physical units.
* For kappa and E, a log transform is often useful because material contrasts can
  span large ranges. Use --field-transform log for single-field mode, or use
  --combined-transform log-robust for combined property-map mode.
* The output mask is on the same grid as the input field used for stationarity.
  Therefore, for QEMSCAN-derived property maps, the mask is directly defined on
  the property-map grid.

Examples
--------
BSE/gray images, full resolution:
    python detect_stationary_domains_general.py \
        1_cut.tif 2_cut.tif 3_cut.tif 4_cut.tif 5_cut.tif 6_cut.tif 7_cut.tif \
        --output-dir stationary_BSE_STRICT \
        --input-type image \
        --stationarity-window 2048 \
        --stride 512 \
        --tau-mu 0.02 \
        --tau-sigma 0.06

Kappa CSV maps on property grid:
    python detect_stationary_domains_general.py \
        data/conductivity/kappaMap_1.csv ... data/conductivity/kappaMap_7.csv \
        --output-dir stationary_kappa_STRICT \
        --input-type csv \
        --field-transform log \
        --stationarity-window 256 \
        --stride 64 \
        --tau-mu 0.02 \
        --tau-sigma 0.06

Combined kappa/E/nu property masks:
    python detect_stationary_domains_general.py \
        --kappa-maps data/conductivity/kappaMap_1.csv ... data/conductivity/kappaMap_7.csv \
        --E-maps "data/Young modulus/EMap_1.csv" ... "data/Young modulus/EMap_7.csv" \
        --nu-maps "data/Poisson ratio/nuMap_1.csv" ... "data/Poisson ratio/nuMap_7.csv" \
        --stationarity-source combined \
        --combined-transform log-robust \
        --output-dir stationary_property_combined_STRICT \
        --stationarity-window 256 \
        --stride 64 \
        --tau-mu 0.02 \
        --tau-sigma 0.06
"""

import argparse
import csv
from pathlib import Path

import numpy as np
from PIL import Image

# Allow very large scientific TIFF/BSE images.
# This is appropriate for local microscopy data supplied by the user.
Image.MAX_IMAGE_PIXELS = None

import matplotlib.pyplot as plt
from scipy.ndimage import binary_closing, binary_opening, label, zoom


# ============================================================
# Loading and field construction
# ============================================================

def infer_input_type(path: Path) -> str:
    """Infer whether the input is a CSV numerical map or an image."""
    ext = path.suffix.lower()
    if ext in [".csv", ".txt", ".dat"]:
        return "csv"
    if ext in [".tif", ".tiff", ".png", ".jpg", ".jpeg", ".bmp"]:
        return "image"
    raise ValueError(f"Cannot infer input type from extension: {path}")


def maybe_downsample_array(arr: np.ndarray, max_side: int, order: int = 1):
    """
    Downsample a 2D array so max(H,W) <= max_side.

    order=1 is bilinear for scalar fields. For masks use order=0.
    """
    H, W = arr.shape
    if max_side is None or max_side <= 0:
        return arr, 1.0
    scale = max(H, W) / float(max_side)
    if scale <= 1.0:
        return arr, 1.0
    new_H = max(1, int(round(H / scale)))
    new_W = max(1, int(round(W / scale)))
    zH = new_H / float(H)
    zW = new_W / float(W)
    out = zoom(arr, (zH, zW), order=order)
    return out.astype(np.float32, copy=False), scale


def load_scalar_field(path, input_type="auto", max_side=0):
    """
    Load one scalar field from an image or CSV numerical map.

    Image files are converted to grayscale intensity. CSV files are loaded as
    numerical property maps and must already contain physical values if physical
    units are desired downstream.
    """
    path = Path(path)
    if input_type == "auto":
        input_type = infer_input_type(path)

    if input_type == "image":
        img = Image.open(path).convert("L")
        w0, h0 = img.size
        arr = np.asarray(img, dtype=np.float32)
        arr, scale = maybe_downsample_array(arr, max_side=max_side, order=1)
        meta = {
            "input_type": "image",
            "original_width": w0,
            "original_height": h0,
            "analysis_width": arr.shape[1],
            "analysis_height": arr.shape[0],
            "downsample_scale": scale,
        }
        return arr, meta

    if input_type == "csv":
        arr = np.loadtxt(path, delimiter=",").astype(np.float32)
        if arr.ndim != 2:
            raise ValueError(f"CSV map must be 2D: {path}")
        h0, w0 = arr.shape
        arr, scale = maybe_downsample_array(arr, max_side=max_side, order=1)
        meta = {
            "input_type": "csv",
            "original_width": w0,
            "original_height": h0,
            "analysis_width": arr.shape[1],
            "analysis_height": arr.shape[0],
            "downsample_scale": scale,
        }
        return arr, meta

    raise ValueError("input_type must be auto, image, or csv")


def robust_median_mad(arr, eps=1e-12):
    """Return median and MAD-based robust scale."""
    finite = np.isfinite(arr)
    if not np.any(finite):
        return 0.0, 1.0
    vals = arr[finite]
    med = float(np.median(vals))
    mad = float(np.median(np.abs(vals - med)))
    scale = 1.4826 * mad
    if not np.isfinite(scale) or scale < eps:
        scale = float(np.std(vals))
    if not np.isfinite(scale) or scale < eps:
        scale = 1.0
    return med, scale


def transform_field(arr, mode="raw", eps=1e-12):
    """
    Transform the scalar field before stationarity detection.

    raw       : use field directly.
    log       : use log(field + offset). Useful for positive contrast fields.
    robust-z  : use robust z-score (median/MAD).
    log-z     : log transform followed by robust z-score.
    """
    arr = np.asarray(arr, dtype=np.float32)
    out = arr.copy()

    if mode == "raw":
        return out

    if mode in ["log", "log-z"]:
        finite = np.isfinite(out)
        if not np.any(finite):
            raise ValueError("Cannot log-transform a field with no finite values.")
        min_val = float(np.nanmin(out[finite]))
        # Shift only if needed. This keeps physical positive maps essentially unchanged.
        shift = 0.0
        if min_val <= 0.0:
            shift = -min_val + eps
        out = np.log(out + shift + eps).astype(np.float32)
        if mode == "log":
            return out

    if mode in ["robust-z", "log-z"]:
        med, scale = robust_median_mad(out, eps=eps)
        out = ((out - med) / scale).astype(np.float32)
        return out

    raise ValueError("field-transform must be raw, log, robust-z, or log-z")


def robust_standardize_for_combined(arr, transform="raw", eps=1e-12):
    """Transform and robust-standardize one channel for combined masks."""
    if transform == "raw":
        tmp = np.asarray(arr, dtype=np.float32)
    elif transform == "log":
        tmp = transform_field(arr, mode="log", eps=eps)
    else:
        raise ValueError("combined channel transform must be raw or log")
    med, scale = robust_median_mad(tmp, eps=eps)
    return ((tmp - med) / scale).astype(np.float32)


def build_combined_field(kappa, E, nu, combined_transform="log-robust", eps=1e-12):
    """
    Build one scalar stationarity field from kappa/E/nu maps.

    raw-robust: robust-standardize kappa, E, nu directly.
    log-robust: log-transform kappa and E before robust standardization;
                nu is robust-standardized directly because it is dimensionless
                and usually bounded.

    The combined scalar is the Euclidean magnitude of the standardized channels,
    divided by sqrt(Nchannels). This produces one strict structural field sensitive
    to changes in any property channel.
    """
    channels = []
    if combined_transform == "raw-robust":
        channels.append(robust_standardize_for_combined(kappa, transform="raw", eps=eps))
        channels.append(robust_standardize_for_combined(E, transform="raw", eps=eps))
        channels.append(robust_standardize_for_combined(nu, transform="raw", eps=eps))
    elif combined_transform == "log-robust":
        channels.append(robust_standardize_for_combined(kappa, transform="log", eps=eps))
        channels.append(robust_standardize_for_combined(E, transform="log", eps=eps))
        channels.append(robust_standardize_for_combined(nu, transform="raw", eps=eps))
    else:
        raise ValueError("combined-transform must be raw-robust or log-robust")

    stack = np.stack(channels, axis=0)
    return np.sqrt(np.nanmean(stack * stack, axis=0)).astype(np.float32)


def load_property_set(args, index):
    """
    Load one kappa/E/nu property-map set and return the stationarity field.
    """
    kappa = E = nu = None
    meta0 = None

    if args.kappa_maps:
        kappa, meta0 = load_scalar_field(args.kappa_maps[index], input_type="csv", max_side=args.max_side)
    if args.E_maps:
        E, metaE = load_scalar_field(args.E_maps[index], input_type="csv", max_side=args.max_side)
        if meta0 is None:
            meta0 = metaE
    if args.nu_maps:
        nu, metaNu = load_scalar_field(args.nu_maps[index], input_type="csv", max_side=args.max_side)
        if meta0 is None:
            meta0 = metaNu

    source = args.stationarity_source
    if source == "kappa":
        if kappa is None:
            raise ValueError("--stationarity-source kappa requires --kappa-maps")
        field = transform_field(kappa, mode=args.field_transform)
        stem = Path(args.kappa_maps[index]).stem
    elif source == "E":
        if E is None:
            raise ValueError("--stationarity-source E requires --E-maps")
        field = transform_field(E, mode=args.field_transform)
        stem = Path(args.E_maps[index]).stem
    elif source == "nu":
        if nu is None:
            raise ValueError("--stationarity-source nu requires --nu-maps")
        field = transform_field(nu, mode=args.field_transform)
        stem = Path(args.nu_maps[index]).stem
    elif source == "combined":
        if kappa is None or E is None or nu is None:
            raise ValueError("--stationarity-source combined requires --kappa-maps, --E-maps, and --nu-maps")
        if not (kappa.shape == E.shape == nu.shape):
            raise ValueError(
                f"Property maps at index {index+1} have different shapes: "
                f"kappa={kappa.shape}, E={E.shape}, nu={nu.shape}"
            )
        field = build_combined_field(kappa, E, nu, combined_transform=args.combined_transform)
        stem = f"property_combined_{index+1}"
    else:
        raise ValueError("stationarity-source must be kappa, E, nu, or combined")

    return field, meta0, stem


# ============================================================
# Stationarity utilities
# ============================================================

def integral_image(arr):
    """Integral image with zero padding."""
    arr = np.asarray(arr, dtype=np.float64)
    return np.pad(arr.cumsum(axis=0).cumsum(axis=1), ((1, 0), (1, 0)), mode="constant")


def window_sum(ii, y0, x0, y1, x1):
    """Sum over arr[y0:y1, x0:x1] from integral image."""
    return ii[y1, x1] - ii[y0, x1] - ii[y1, x0] + ii[y0, x0]


def compute_window_stats_fast(img, R, stride):
    """
    Compute local mean/std on a regular grid of R x R windows.

    NaN/inf values are replaced by the finite median before scanning. This keeps
    the integral-image calculation fast and avoids undefined local statistics.
    """
    img = np.asarray(img, dtype=np.float32)
    finite = np.isfinite(img)
    if not np.any(finite):
        raise ValueError("Input field contains no finite values.")
    if not np.all(finite):
        med = np.nanmedian(img[finite])
        img = img.copy()
        img[~finite] = med

    H, W = img.shape
    if R > H or R > W:
        raise ValueError(f"stationarity-window R={R} is larger than image size {H} x {W}")

    y_starts = list(range(0, H - R + 1, stride))
    x_starts = list(range(0, W - R + 1, stride))
    if not y_starts or not x_starts:
        raise ValueError("No stationarity windows generated. Check R and stride.")
    if y_starts[-1] != H - R:
        y_starts.append(H - R)
    if x_starts[-1] != W - R:
        x_starts.append(W - R)

    ii = integral_image(img)
    ii2 = integral_image(img * img)
    means = np.zeros((len(y_starts), len(x_starts)), dtype=np.float64)
    stds = np.zeros_like(means)
    area = float(R * R)

    for iy, y0 in enumerate(y_starts):
        y1 = y0 + R
        for ix, x0 in enumerate(x_starts):
            x1 = x0 + R
            s1 = window_sum(ii, y0, x0, y1, x1)
            s2 = window_sum(ii2, y0, x0, y1, x1)
            mu = s1 / area
            var = max(s2 / area - mu * mu, 0.0)
            means[iy, ix] = mu
            stds[iy, ix] = np.sqrt(var)

    centers_y = np.array(y_starts, dtype=float) + 0.5 * R
    centers_x = np.array(x_starts, dtype=float) + 0.5 * R
    return centers_y, centers_x, means, stds


def robust_stationary_grid(means, stds, tau_mu=0.03, tau_sigma=0.08, eps=1e-12):
    """Classify coarse stationarity windows using median references."""
    mu_ref = np.nanmedian(means)
    std_ref = np.nanmedian(stds)
    mu_res = np.abs(means - mu_ref) / (abs(mu_ref) + eps)
    std_res = np.abs(stds - std_ref) / (abs(std_ref) + eps)
    stat_grid = (mu_res <= tau_mu) & (std_res <= tau_sigma)
    return stat_grid, mu_res, std_res, mu_ref, std_ref


def clean_stationary_grid(stat_grid, min_component_windows=4, do_open_close=True):
    """Morphological cleanup and connected-component filtering on coarse grid."""
    if stat_grid.size == 0:
        return stat_grid
    cleaned = stat_grid.astype(bool)
    if do_open_close:
        cleaned = binary_opening(cleaned, structure=np.ones((2, 2), dtype=bool))
        cleaned = binary_closing(cleaned, structure=np.ones((2, 2), dtype=bool))
    if min_component_windows <= 1:
        return cleaned
    lab, nlab = label(cleaned)
    out = np.zeros_like(cleaned, dtype=bool)
    for k in range(1, nlab + 1):
        comp = lab == k
        if comp.sum() >= min_component_windows:
            out |= comp
    return out


def grid_to_pixel_mask(stat_grid, image_shape, centers_y, centers_x, R):
    """Convert accepted coarse stationarity windows to a pixel-level mask."""
    H, W = image_shape
    mask = np.zeros((H, W), dtype=bool)
    for iy, cy in enumerate(centers_y):
        for ix, cx in enumerate(centers_x):
            if not stat_grid[iy, ix]:
                continue
            y0 = int(round(cy - 0.5 * R))
            x0 = int(round(cx - 0.5 * R))
            y1 = min(y0 + R, H)
            x1 = min(x0 + R, W)
            y0 = max(y0, 0)
            x0 = max(x0, 0)
            mask[y0:y1, x0:x1] = True
    return mask


def largest_component(mask):
    """Keep the largest connected component of a pixel mask."""
    lab, nlab = label(mask)
    if nlab == 0:
        return mask
    sizes = np.array([(lab == k).sum() for k in range(1, nlab + 1)])
    kmax = int(np.argmax(sizes)) + 1
    return lab == kmax


# ============================================================
# Output utilities
# ============================================================

def save_mask_tif(mask, path):
    Image.fromarray(mask.astype(np.uint8) * 255).save(path)


def save_mask_png(mask, path):
    Image.fromarray(mask.astype(np.uint8) * 255).save(path)


def save_overlay(field, mask, path, title=None, dpi=300, cmap="gray"):
    """Save field with red stationary-mask overlay."""
    fig, ax = plt.subplots(figsize=(8, 7))
    im = ax.imshow(field, cmap=cmap, origin="upper")
    overlay = np.zeros((*mask.shape, 4), dtype=float)
    overlay[..., 0] = 1.0
    overlay[..., 3] = mask.astype(float) * 0.35
    ax.imshow(overlay, origin="upper")
    if title:
        ax.set_title(title)
    ax.set_xlabel("x [analysis pixels]")
    ax.set_ylabel("y [analysis pixels]")
    cbar = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    cbar.set_label("stationarity field value")
    fig.tight_layout()
    fig.savefig(path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


def save_grid_diagnostics_csv(path, centers_y, centers_x, means, stds, mu_res, std_res, stat_raw, stat_clean):
    """Save local stationarity-window diagnostics."""
    with open(path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow([
            "iy", "ix", "center_y", "center_x", "mean", "std",
            "mu_residual", "std_residual", "stationary_raw", "stationary_clean",
        ])
        for iy, cy in enumerate(centers_y):
            for ix, cx in enumerate(centers_x):
                writer.writerow([
                    iy, ix, float(cy), float(cx), float(means[iy, ix]), float(stds[iy, ix]),
                    float(mu_res[iy, ix]), float(std_res[iy, ix]),
                    int(stat_raw[iy, ix]), int(stat_clean[iy, ix]),
                ])


def save_summary_plot(field, mask, means, stds, mu_res, std_res, stat_clean, output_path, title, dpi=300, cmap="gray"):
    """Save four-panel diagnostic summary for one field."""
    fig, axes = plt.subplots(2, 2, figsize=(11, 9))

    ax = axes[0, 0]
    im0 = ax.imshow(field, cmap=cmap, origin="upper")
    ax.set_title("Input stationarity field")
    ax.set_xlabel("x")
    ax.set_ylabel("y")
    fig.colorbar(im0, ax=ax, shrink=0.80)

    ax = axes[0, 1]
    ax.imshow(field, cmap=cmap, origin="upper")
    overlay = np.zeros((*mask.shape, 4), dtype=float)
    overlay[..., 0] = 1.0
    overlay[..., 3] = mask.astype(float) * 0.35
    ax.imshow(overlay, origin="upper")
    ax.set_title("Stationary-domain mask")
    ax.set_xlabel("x")
    ax.set_ylabel("y")

    ax = axes[1, 0]
    im = ax.imshow(means, origin="upper", aspect="auto")
    if np.any(stat_clean):
        ax.contour(stat_clean.astype(float), levels=[0.5], colors="white", linewidths=1.0)
    fig.colorbar(im, ax=ax, shrink=0.85)
    ax.set_title("Local window mean")
    ax.set_xlabel("window-grid x")
    ax.set_ylabel("window-grid y")

    ax = axes[1, 1]
    combined_res = np.maximum(mu_res, std_res)
    im = ax.imshow(combined_res, origin="upper", aspect="auto")
    if np.any(stat_clean):
        ax.contour(stat_clean.astype(float), levels=[0.5], colors="white", linewidths=1.0)
    fig.colorbar(im, ax=ax, shrink=0.85)
    ax.set_title("Max normalized residual")
    ax.set_xlabel("window-grid x")
    ax.set_ylabel("window-grid y")

    fig.suptitle(title)
    fig.tight_layout()
    fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


# ============================================================
# Processing
# ============================================================

def process_field(field, stem, meta, args, output_dir):
    """Compute and save stationary mask for one scalar field."""
    print("\nLoaded field")
    print("=" * 80)
    print(f"Field/stem                    : {stem}")
    print(f"Input type                    : {meta.get('input_type', 'property-set')}")
    print(f"Original size                 : {meta['original_width']} x {meta['original_height']} pixels")
    print(f"Analysis size                 : {meta['analysis_width']} x {meta['analysis_height']} pixels")
    print(f"Downsample scale              : {meta['downsample_scale']:.6g}")
    print(f"Stationarity window           : {args.stationarity_window} analysis pixels")
    print(f"Stride                        : {args.stride} analysis pixels")
    print(f"tau_mu                        : {args.tau_mu}")
    print(f"tau_sigma                     : {args.tau_sigma}")
    print("=" * 80)

    centers_y, centers_x, means, stds = compute_window_stats_fast(
        field, R=args.stationarity_window, stride=args.stride
    )
    stat_raw, mu_res, std_res, mu_ref, std_ref = robust_stationary_grid(
        means, stds, tau_mu=args.tau_mu, tau_sigma=args.tau_sigma
    )
    stat_clean = clean_stationary_grid(
        stat_raw,
        min_component_windows=args.min_component_windows,
        do_open_close=(not args.no_morphology),
    )
    mask = grid_to_pixel_mask(
        stat_clean,
        image_shape=field.shape,
        centers_y=centers_y,
        centers_x=centers_x,
        R=args.stationarity_window,
    )
    if args.keep_largest_component:
        mask = largest_component(mask)

    stat_fraction_grid = float(stat_clean.mean())
    stat_fraction_pixel = float(mask.mean())

    print("Stationary-domain result")
    print("-" * 80)
    print(f"Reference local mean          : {mu_ref:.8g}")
    print(f"Reference local std           : {std_ref:.8g}")
    print(f"Accepted grid-window fraction : {stat_fraction_grid:.8g}")
    print(f"Accepted pixel fraction       : {stat_fraction_pixel:.8g}")
    print("-" * 80)

    mask_png = output_dir / f"{stem}_stationary_mask.png"
    mask_tif = output_dir / f"{stem}_stationary_mask.tif"
    overlay_png = output_dir / f"{stem}_stationary_overlay.png"
    summary_png = output_dir / f"{stem}_stationary_summary.png"
    csv_path = output_dir / f"{stem}_stationary_windows.csv"

    save_mask_png(mask, mask_png)
    save_mask_tif(mask, mask_tif)
    save_overlay(field, mask, overlay_png, title=f"{stem}: stationary-domain mask", dpi=args.dpi, cmap=args.cmap)
    save_summary_plot(field, mask, means, stds, mu_res, std_res, stat_clean,
                      summary_png, title=f"{stem}: stationarity diagnostics", dpi=args.dpi, cmap=args.cmap)
    save_grid_diagnostics_csv(csv_path, centers_y, centers_x, means, stds, mu_res, std_res, stat_raw, stat_clean)

    return {
        "field": stem,
        "analysis_height": field.shape[0],
        "analysis_width": field.shape[1],
        "downsample_scale": meta["downsample_scale"],
        "stationarity_window": args.stationarity_window,
        "stride": args.stride,
        "tau_mu": args.tau_mu,
        "tau_sigma": args.tau_sigma,
        "mu_ref": mu_ref,
        "std_ref": std_ref,
        "stationary_grid_fraction": stat_fraction_grid,
        "stationary_pixel_fraction": stat_fraction_pixel,
        "mask_png": str(mask_png),
        "mask_tif": str(mask_tif),
        "overlay_png": str(overlay_png),
        "summary_png": str(summary_png),
        "csv": str(csv_path),
    }


def save_global_summary(rows, output_dir):
    path = output_dir / "stationary_domain_global_summary.csv"
    keys = [
        "field", "analysis_height", "analysis_width", "downsample_scale",
        "stationarity_window", "stride", "tau_mu", "tau_sigma", "mu_ref", "std_ref",
        "stationary_grid_fraction", "stationary_pixel_fraction",
        "mask_png", "mask_tif", "overlay_png", "summary_png", "csv",
    ]
    with open(path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=keys)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)
    print("\nSaved global summary:")
    print(f"  {path}")


# ============================================================
# CLI
# ============================================================

def parse_args():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description=(
            "Detect approximately stationary domains in BSE images or numerical "
            "property maps. Outputs strict pixel masks and diagnostic figures."
        ),
    )

    parser.add_argument(
        "inputs",
        nargs="*",
        help=(
            "Input scalar fields for single-field mode. Can be images or CSV maps. "
            "Do not use this together with --kappa-maps/--E-maps/--nu-maps."
        ),
    )

    parser.add_argument("--input-type", choices=["auto", "image", "csv"], default="auto",
                        help="Input type for positional inputs.")
    parser.add_argument("--field-transform", choices=["raw", "log", "robust-z", "log-z"], default="raw",
                        help=(
                            "Transform applied before stationarity detection. Use log or log-z for "
                            "positive high-contrast property maps such as kappa and E."
                        ))

    # Property-map mode. These are CSV numerical maps, not visualization TIFFs.
    parser.add_argument("--kappa-maps", nargs="+", default=None,
                        help="CSV kappa maps [W m^-1 K^-1] for property-map mode.")
    parser.add_argument("--E-maps", nargs="+", default=None,
                        help="CSV Young-modulus maps [GPa] for property-map mode.")
    parser.add_argument("--nu-maps", nargs="+", default=None,
                        help="CSV Poisson-ratio maps [-] for property-map mode.")
    parser.add_argument("--stationarity-source", choices=["kappa", "E", "nu", "combined"], default="kappa",
                        help="Which property field defines the stationary mask in property-map mode.")
    parser.add_argument("--combined-transform", choices=["raw-robust", "log-robust"], default="log-robust",
                        help=(
                            "How to build a combined kappa/E/nu mask. log-robust applies log to kappa "
                            "and E before robust standardization; nu is used directly."
                        ))

    parser.add_argument("--output-dir", default="stationary_domains_general",
                        help="Output directory for masks, overlays, and diagnostics.")
    parser.add_argument("--max-side", type=int, default=0,
                        help="Downsample so max image/map side <= max-side. Use 0 for full resolution.")
    parser.add_argument("--stationarity-window", type=int, default=256,
                        help="Local square stationarity window size R in analysis pixels.")
    parser.add_argument("--stride", type=int, default=64,
                        help="Stride between local stationarity windows in analysis pixels.")
    parser.add_argument("--tau-mu", type=float, default=0.02,
                        help="Relative tolerance for local-mean stationarity.")
    parser.add_argument("--tau-sigma", type=float, default=0.06,
                        help="Relative tolerance for local-standard-deviation stationarity.")
    parser.add_argument("--min-component-windows", type=int, default=4,
                        help="Minimum connected-component size in coarse stationarity-window grid cells.")
    parser.add_argument("--keep-largest-component", action="store_true",
                        help="Keep only the largest connected stationary component in the final pixel mask.")
    parser.add_argument("--no-morphology", action="store_true",
                        help="Disable opening/closing cleanup on the coarse stationarity grid.")
    parser.add_argument("--cmap", default="viridis",
                        help="Colormap used for summary/overlay figures.")
    parser.add_argument("--dpi", type=int, default=300,
                        help="DPI for PNG diagnostic figures.")

    return parser.parse_args()


def validate_args(args):
    prop_mode = any([args.kappa_maps, args.E_maps, args.nu_maps])
    single_mode = len(args.inputs) > 0
    if prop_mode and single_mode:
        raise ValueError("Use either positional inputs OR --kappa-maps/--E-maps/--nu-maps, not both.")
    if not prop_mode and not single_mode:
        raise ValueError("Provide positional inputs or property-map lists.")
    if prop_mode:
        lengths = []
        for x in [args.kappa_maps, args.E_maps, args.nu_maps]:
            if x is not None:
                lengths.append(len(x))
        if len(set(lengths)) != 1:
            raise ValueError("All provided property-map lists must have the same length.")
        if args.stationarity_source == "combined":
            if args.kappa_maps is None or args.E_maps is None or args.nu_maps is None:
                raise ValueError("combined source requires --kappa-maps, --E-maps, and --nu-maps.")


def main():
    args = parse_args()
    validate_args(args)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    rows = []

    prop_mode = any([args.kappa_maps, args.E_maps, args.nu_maps])
    if prop_mode:
        n = len(args.kappa_maps or args.E_maps or args.nu_maps)
        print("\nProperty-map stationary-domain detection")
        print("=" * 80)
        print(f"Number of property sets       : {n}")
        print(f"Stationarity source           : {args.stationarity_source}")
        print(f"Combined transform            : {args.combined_transform}")
        print("=" * 80)
        for i in range(n):
            field, meta, stem = load_property_set(args, i)
            if args.stationarity_source != "combined":
                stem = f"{args.stationarity_source}_{i+1}_{stem}"
            row = process_field(field, stem, meta, args, output_dir)
            rows.append(row)
    else:
        print("\nSingle-field stationary-domain detection")
        print("=" * 80)
        print(f"Number of inputs              : {len(args.inputs)}")
        print(f"Input type                    : {args.input_type}")
        print(f"Field transform               : {args.field_transform}")
        print("=" * 80)
        for path in args.inputs:
            path = Path(path)
            field, meta = load_scalar_field(path, input_type=args.input_type, max_side=args.max_side)
            field = transform_field(field, mode=args.field_transform)
            stem = path.stem
            if args.field_transform != "raw":
                stem = f"{stem}_{args.field_transform}"
            row = process_field(field, stem, meta, args, output_dir)
            rows.append(row)

    save_global_summary(rows, output_dir)
    print("\nDone.")
    print("The stationary-domain masks are saved in:")
    print(f"  {output_dir}")


if __name__ == "__main__":
    main()
